/**
 * Mock Data — Demo Mode
 * Used when Supabase credentials are not configured.
 * Provides realistic sample data for UI development and demonstration.
 */

import type { Exam, Submission } from "./supabase";

export const MOCK_EXAMS: Exam[] = [
  {
    id: "exam-001",
    unit_code: "COMP-204",
    course_name: "Computer Science Fundamentals",
    created_at: "2024-01-15T08:00:00Z",
    payload: {
      title: "Computer Science Fundamentals — CAT 1",
      duration_minutes: 90,
      total_marks: 100,
      instructions:
        "Answer ALL questions in Section A and ANY TWO questions in Section B. Write clearly and legibly.",
      section_a: {
        title: "Section A — Multiple Choice Questions",
        instructions:
          "Circle the correct answer for each question. Each question carries 2 marks.",
        total_marks: 40,
        questions: [
          {
            id: "a1",
            text: "Which data structure uses LIFO (Last In, First Out) ordering?",
            type: "mcq",
            options: ["Queue", "Stack", "Linked List", "Binary Tree"],
            correct_answer: 1,
            marks: 2,
          },
          {
            id: "a2",
            text: "What is the time complexity of binary search?",
            type: "mcq",
            options: ["O(n)", "O(n²)", "O(log n)", "O(1)"],
            correct_answer: 2,
            marks: 2,
          },
          {
            id: "a3",
            text: "Which of the following is NOT an object-oriented programming language?",
            type: "mcq",
            options: ["Java", "Python", "C", "C++"],
            correct_answer: 2,
            marks: 2,
          },
          {
            id: "a4",
            text: "What does HTML stand for?",
            type: "mcq",
            options: [
              "Hyper Text Markup Language",
              "High Tech Modern Language",
              "Hyper Transfer Markup Language",
              "Home Tool Markup Language",
            ],
            correct_answer: 0,
            marks: 2,
          },
          {
            id: "a5",
            text: "A database management system (DBMS) is used to:",
            type: "mcq",
            options: [
              "Design hardware components",
              "Manage and organize data",
              "Create operating systems",
              "Develop mobile applications",
            ],
            correct_answer: 1,
            marks: 2,
          },
          {
            id: "a6",
            text: "Which sorting algorithm has the best average-case time complexity?",
            type: "mcq",
            options: ["Bubble Sort", "Selection Sort", "Quick Sort", "Insertion Sort"],
            correct_answer: 2,
            marks: 2,
          },
          {
            id: "a7",
            text: "In a relational database, a primary key:",
            type: "mcq",
            options: [
              "Can contain duplicate values",
              "Uniquely identifies each record",
              "Is always a numeric field",
              "Can be NULL",
            ],
            correct_answer: 1,
            marks: 2,
          },
          {
            id: "a8",
            text: "What is the output of: print(2 ** 3) in Python?",
            type: "mcq",
            options: ["6", "8", "9", "5"],
            correct_answer: 1,
            marks: 2,
          },
          {
            id: "a9",
            text: "Which protocol is used to send emails?",
            type: "mcq",
            options: ["HTTP", "FTP", "SMTP", "TCP"],
            correct_answer: 2,
            marks: 2,
          },
          {
            id: "a10",
            text: "An IP address version 4 (IPv4) consists of how many bits?",
            type: "mcq",
            options: ["16 bits", "32 bits", "64 bits", "128 bits"],
            correct_answer: 1,
            marks: 2,
          },
          {
            id: "a11",
            text: "Which of the following is a non-volatile storage device?",
            type: "mcq",
            options: ["RAM", "Cache", "Hard Disk Drive", "CPU Register"],
            correct_answer: 2,
            marks: 2,
          },
          {
            id: "a12",
            text: "The binary representation of decimal 10 is:",
            type: "mcq",
            options: ["1010", "1100", "1001", "0110"],
            correct_answer: 0,
            marks: 2,
          },
          {
            id: "a13",
            text: "Which layer of the OSI model handles routing?",
            type: "mcq",
            options: ["Physical", "Data Link", "Network", "Transport"],
            correct_answer: 2,
            marks: 2,
          },
          {
            id: "a14",
            text: "What does CSS stand for?",
            type: "mcq",
            options: [
              "Computer Style Sheets",
              "Cascading Style Sheets",
              "Creative Style System",
              "Colorful Style Sheets",
            ],
            correct_answer: 1,
            marks: 2,
          },
          {
            id: "a15",
            text: "Which of the following is an example of an interpreted language?",
            type: "mcq",
            options: ["C", "C++", "Java", "Python"],
            correct_answer: 3,
            marks: 2,
          },
          {
            id: "a16",
            text: "A firewall is primarily used to:",
            type: "mcq",
            options: [
              "Speed up internet connection",
              "Filter network traffic",
              "Store backup data",
              "Compress files",
            ],
            correct_answer: 1,
            marks: 2,
          },
          {
            id: "a17",
            text: "What is the function of an operating system?",
            type: "mcq",
            options: [
              "Run application software only",
              "Manage hardware and software resources",
              "Connect to the internet",
              "Store user files",
            ],
            correct_answer: 1,
            marks: 2,
          },
          {
            id: "a18",
            text: "Which of the following is a high-level programming language?",
            type: "mcq",
            options: ["Machine Code", "Assembly Language", "Python", "Binary"],
            correct_answer: 2,
            marks: 2,
          },
          {
            id: "a19",
            text: "In object-oriented programming, encapsulation refers to:",
            type: "mcq",
            options: [
              "Hiding internal implementation details",
              "Inheriting properties from a parent class",
              "Creating multiple instances of a class",
              "Overriding methods in subclasses",
            ],
            correct_answer: 0,
            marks: 2,
          },
          {
            id: "a20",
            text: "Which of the following is NOT a type of computer network?",
            type: "mcq",
            options: ["LAN", "WAN", "MAN", "TAN"],
            correct_answer: 3,
            marks: 2,
          },
        ],
      },
      section_b: {
        title: "Section B — Structured Questions",
        instructions:
          "Answer ANY TWO questions from this section. Each question carries 30 marks. Show all working where applicable.",
        total_marks: 60,
        questions: [
          {
            id: "b1",
            text: "Explain the four main pillars of Object-Oriented Programming (OOP). For each pillar, provide a real-world analogy and a code example in any programming language of your choice. (30 marks)",
            type: "short_answer",
            correct_answer:
              "Encapsulation, Inheritance, Polymorphism, Abstraction — each with explanation and example",
            marks: 30,
          },
          {
            id: "b2",
            text: "Describe the OSI (Open Systems Interconnection) model. List all seven layers, explain the function of each layer, and give an example of a protocol or technology associated with each layer. (30 marks)",
            type: "short_answer",
            correct_answer:
              "Physical, Data Link, Network, Transport, Session, Presentation, Application — each with function and protocol",
            marks: 30,
          },
          {
            id: "b3",
            text: "Compare and contrast relational databases (SQL) and non-relational databases (NoSQL). Discuss their structures, use cases, advantages, and disadvantages. Provide examples of each type. (30 marks)",
            type: "short_answer",
            correct_answer:
              "Structured vs unstructured, ACID vs BASE, MySQL/PostgreSQL vs MongoDB/Redis, use cases",
            marks: 30,
          },
        ],
      },
    },
  },
  {
    id: "exam-002",
    unit_code: "ELEC-101",
    course_name: "Electrical Installations",
    created_at: "2024-01-20T09:00:00Z",
    payload: {
      title: "Electrical Installations — End of Term Exam",
      duration_minutes: 120,
      total_marks: 100,
      instructions:
        "Answer ALL questions in Section A and ANY TWO questions in Section B.",
      section_a: {
        title: "Section A — Multiple Choice",
        instructions: "Each question carries 2 marks.",
        total_marks: 40,
        questions: [
          {
            id: "a1",
            text: "What is the SI unit of electrical resistance?",
            type: "mcq",
            options: ["Volt", "Ampere", "Ohm", "Watt"],
            correct_answer: 2,
            marks: 2,
          },
          {
            id: "a2",
            text: "Ohm's Law states that V = ?",
            type: "mcq",
            options: ["I + R", "I × R", "I / R", "I - R"],
            correct_answer: 1,
            marks: 2,
          },
          {
            id: "a3",
            text: "Which color wire is typically used for earth/ground in Kenya?",
            type: "mcq",
            options: ["Red", "Black", "Green/Yellow", "Blue"],
            correct_answer: 2,
            marks: 2,
          },
          {
            id: "a4",
            text: "A circuit breaker is used to:",
            type: "mcq",
            options: [
              "Increase voltage",
              "Protect against overcurrent",
              "Store electrical energy",
              "Convert AC to DC",
            ],
            correct_answer: 1,
            marks: 2,
          },
          {
            id: "a5",
            text: "What is the standard mains voltage in Kenya?",
            type: "mcq",
            options: ["110V", "220V", "240V", "380V"],
            correct_answer: 2,
            marks: 2,
          },
        ],
      },
      section_b: {
        title: "Section B — Structured Questions",
        instructions: "Answer ANY TWO questions. Each carries 30 marks.",
        total_marks: 60,
        questions: [
          {
            id: "b1",
            text: "Describe the procedure for wiring a domestic ring main circuit. Include safety precautions and the materials required. (30 marks)",
            type: "short_answer",
            correct_answer: "Ring main wiring procedure with safety measures",
            marks: 30,
          },
          {
            id: "b2",
            text: "Explain the difference between series and parallel circuits. Calculate the total resistance when three resistors of 4Ω, 6Ω, and 12Ω are connected in parallel. (30 marks)",
            type: "short_answer",
            correct_answer: "Series vs parallel explanation + calculation: 1/R = 1/4 + 1/6 + 1/12 = 2Ω",
            marks: 30,
          },
        ],
      },
    },
  },
  {
    id: "exam-003",
    unit_code: "MECH-301",
    course_name: "Mechanical Engineering Principles",
    created_at: "2024-02-01T10:00:00Z",
    payload: {
      title: "Mechanical Engineering Principles — CAT 2",
      duration_minutes: 90,
      total_marks: 100,
      instructions: "Answer ALL questions in Section A and Section B.",
      section_a: {
        title: "Section A — Objective",
        instructions: "Each question carries 2 marks.",
        total_marks: 40,
        questions: [
          {
            id: "a1",
            text: "Newton's Second Law of Motion states that Force equals:",
            type: "mcq",
            options: ["mass × velocity", "mass × acceleration", "mass / acceleration", "velocity / time"],
            correct_answer: 1,
            marks: 2,
          },
          {
            id: "a2",
            text: "The SI unit of pressure is:",
            type: "mcq",
            options: ["Newton", "Pascal", "Joule", "Watt"],
            correct_answer: 1,
            marks: 2,
          },
        ],
      },
      section_b: {
        title: "Section B — Theory",
        instructions: "Answer any TWO. Each carries 30 marks.",
        total_marks: 60,
        questions: [
          {
            id: "b1",
            text: "Describe the working principle of a four-stroke internal combustion engine. Include a labeled diagram description and explain each stroke. (30 marks)",
            type: "short_answer",
            correct_answer: "Intake, compression, power, exhaust strokes with explanations",
            marks: 30,
          },
        ],
      },
    },
  },
];

export const MOCK_SUBMISSIONS: Submission[] = [
  {
    id: "sub-001",
    unit_code: "COMP-204",
    student_name: "Alice Wanjiku Kamau",
    reg_number: "MTTI/2024/001",
    section_a: [
      { question_id: "a1", answer: 1, marks_awarded: 2 },
      { question_id: "a2", answer: 2, marks_awarded: 2 },
      { question_id: "a3", answer: 2, marks_awarded: 2 },
      { question_id: "a4", answer: 0, marks_awarded: 2 },
      { question_id: "a5", answer: 1, marks_awarded: 2 },
      { question_id: "a6", answer: 2, marks_awarded: 2 },
      { question_id: "a7", answer: 1, marks_awarded: 2 },
      { question_id: "a8", answer: 1, marks_awarded: 2 },
      { question_id: "a9", answer: 2, marks_awarded: 2 },
      { question_id: "a10", answer: 1, marks_awarded: 2 },
      { question_id: "a11", answer: 2, marks_awarded: 2 },
      { question_id: "a12", answer: 0, marks_awarded: 2 },
      { question_id: "a13", answer: 2, marks_awarded: 2 },
      { question_id: "a14", answer: 1, marks_awarded: 2 },
      { question_id: "a15", answer: 3, marks_awarded: 2 },
      { question_id: "a16", answer: 1, marks_awarded: 2 },
      { question_id: "a17", answer: 1, marks_awarded: 2 },
      { question_id: "a18", answer: 2, marks_awarded: 2 },
      { question_id: "a19", answer: 0, marks_awarded: 2 },
      { question_id: "a20", answer: 3, marks_awarded: 2 },
    ],
    section_b: [
      { question_id: "b1", answer: "Encapsulation bundles data and methods. Inheritance allows classes to derive from parent classes. Polymorphism allows methods to behave differently based on context. Abstraction hides implementation details.", marks_awarded: 26 },
      { question_id: "b2", answer: "The OSI model has 7 layers: Physical (cables), Data Link (MAC), Network (IP routing), Transport (TCP/UDP), Session (connections), Presentation (encoding), Application (HTTP, FTP).", marks_awarded: 28 },
    ],
    status: "graded",
    total_score: 94,
    created_at: "2024-01-20T10:30:00Z",
  },
  {
    id: "sub-002",
    unit_code: "COMP-204",
    student_name: "Brian Otieno Odhiambo",
    reg_number: "MTTI/2024/002",
    section_a: [
      { question_id: "a1", answer: 1, marks_awarded: 2 },
      { question_id: "a2", answer: 1, marks_awarded: 0 },
      { question_id: "a3", answer: 2, marks_awarded: 2 },
      { question_id: "a4", answer: 0, marks_awarded: 2 },
      { question_id: "a5", answer: 1, marks_awarded: 2 },
      { question_id: "a6", answer: 0, marks_awarded: 0 },
      { question_id: "a7", answer: 1, marks_awarded: 2 },
      { question_id: "a8", answer: 1, marks_awarded: 2 },
      { question_id: "a9", answer: 2, marks_awarded: 2 },
      { question_id: "a10", answer: 1, marks_awarded: 2 },
      { question_id: "a11", answer: 2, marks_awarded: 2 },
      { question_id: "a12", answer: 0, marks_awarded: 2 },
      { question_id: "a13", answer: 2, marks_awarded: 2 },
      { question_id: "a14", answer: 1, marks_awarded: 2 },
      { question_id: "a15", answer: 2, marks_awarded: 0 },
      { question_id: "a16", answer: 1, marks_awarded: 2 },
      { question_id: "a17", answer: 1, marks_awarded: 2 },
      { question_id: "a18", answer: 2, marks_awarded: 2 },
      { question_id: "a19", answer: 0, marks_awarded: 2 },
      { question_id: "a20", answer: 3, marks_awarded: 2 },
    ],
    section_b: [
      { question_id: "b1", answer: "OOP has four pillars: encapsulation (data hiding), inheritance (parent-child classes), polymorphism (many forms), abstraction (hiding complexity).", marks_awarded: 20 },
      { question_id: "b3", answer: "SQL databases are relational with tables and rows. NoSQL databases like MongoDB use documents. SQL uses ACID properties while NoSQL uses BASE.", marks_awarded: 18 },
    ],
    status: "graded",
    total_score: 72,
    created_at: "2024-01-20T10:45:00Z",
  },
  {
    id: "sub-003",
    unit_code: "COMP-204",
    student_name: "Catherine Muthoni Njoroge",
    reg_number: "MTTI/2024/003",
    section_a: [
      { question_id: "a1", answer: 1, marks_awarded: 2 },
      { question_id: "a2", answer: 2, marks_awarded: 2 },
      { question_id: "a3", answer: 2, marks_awarded: 2 },
      { question_id: "a4", answer: 0, marks_awarded: 2 },
      { question_id: "a5", answer: 1, marks_awarded: 2 },
      { question_id: "a6", answer: 2, marks_awarded: 2 },
      { question_id: "a7", answer: 1, marks_awarded: 2 },
      { question_id: "a8", answer: 1, marks_awarded: 2 },
      { question_id: "a9", answer: 2, marks_awarded: 2 },
      { question_id: "a10", answer: 1, marks_awarded: 2 },
      { question_id: "a11", answer: 2, marks_awarded: 2 },
      { question_id: "a12", answer: 0, marks_awarded: 2 },
      { question_id: "a13", answer: 2, marks_awarded: 2 },
      { question_id: "a14", answer: 1, marks_awarded: 2 },
      { question_id: "a15", answer: 3, marks_awarded: 2 },
      { question_id: "a16", answer: 1, marks_awarded: 2 },
      { question_id: "a17", answer: 1, marks_awarded: 2 },
      { question_id: "a18", answer: 2, marks_awarded: 2 },
      { question_id: "a19", answer: 0, marks_awarded: 2 },
      { question_id: "a20", answer: 3, marks_awarded: 2 },
    ],
    section_b: [
      { question_id: "b2", answer: "OSI model: Layer 1 Physical (cables, hubs), Layer 2 Data Link (switches, MAC addresses), Layer 3 Network (routers, IP), Layer 4 Transport (TCP, UDP), Layer 5 Session, Layer 6 Presentation, Layer 7 Application (HTTP, DNS, FTP).", marks_awarded: 27 },
      { question_id: "b3", answer: "Relational databases use structured tables with SQL. Non-relational use flexible schemas. MySQL is SQL, MongoDB is NoSQL. SQL is better for complex queries, NoSQL for scalability.", marks_awarded: 22 },
    ],
    status: "graded",
    total_score: 89,
    created_at: "2024-01-20T11:00:00Z",
  },
  {
    id: "sub-004",
    unit_code: "COMP-204",
    student_name: "David Kipchoge Rotich",
    reg_number: "MTTI/2024/004",
    section_a: [
      { question_id: "a1", answer: 0, marks_awarded: 0 },
      { question_id: "a2", answer: 2, marks_awarded: 2 },
      { question_id: "a3", answer: 2, marks_awarded: 2 },
      { question_id: "a4", answer: 0, marks_awarded: 2 },
      { question_id: "a5", answer: 1, marks_awarded: 2 },
      { question_id: "a6", answer: 2, marks_awarded: 2 },
      { question_id: "a7", answer: 1, marks_awarded: 2 },
      { question_id: "a8", answer: 1, marks_awarded: 2 },
      { question_id: "a9", answer: 0, marks_awarded: 0 },
      { question_id: "a10", answer: 1, marks_awarded: 2 },
      { question_id: "a11", answer: 2, marks_awarded: 2 },
      { question_id: "a12", answer: 0, marks_awarded: 2 },
      { question_id: "a13", answer: 2, marks_awarded: 2 },
      { question_id: "a14", answer: 1, marks_awarded: 2 },
      { question_id: "a15", answer: 3, marks_awarded: 2 },
      { question_id: "a16", answer: 1, marks_awarded: 2 },
      { question_id: "a17", answer: 1, marks_awarded: 2 },
      { question_id: "a18", answer: 2, marks_awarded: 2 },
      { question_id: "a19", answer: 0, marks_awarded: 2 },
      { question_id: "a20", answer: 3, marks_awarded: 2 },
    ],
    section_b: [
      { question_id: "b1", answer: "OOP pillars are encapsulation, inheritance, polymorphism, abstraction.", marks_awarded: 15 },
      { question_id: "b2", answer: "OSI has 7 layers.", marks_awarded: 10 },
    ],
    status: "graded",
    total_score: 61,
    created_at: "2024-01-20T11:15:00Z",
  },
  {
    id: "sub-005",
    unit_code: "COMP-204",
    student_name: "Esther Akinyi Ouma",
    reg_number: "MTTI/2024/005",
    section_a: [
      { question_id: "a1", answer: 1, marks_awarded: 2 },
      { question_id: "a2", answer: 2, marks_awarded: 2 },
      { question_id: "a3", answer: 2, marks_awarded: 2 },
      { question_id: "a4", answer: 0, marks_awarded: 2 },
      { question_id: "a5", answer: 1, marks_awarded: 2 },
      { question_id: "a6", answer: 2, marks_awarded: 2 },
      { question_id: "a7", answer: 1, marks_awarded: 2 },
      { question_id: "a8", answer: 1, marks_awarded: 2 },
      { question_id: "a9", answer: 2, marks_awarded: 2 },
      { question_id: "a10", answer: 1, marks_awarded: 2 },
      { question_id: "a11", answer: 2, marks_awarded: 2 },
      { question_id: "a12", answer: 0, marks_awarded: 2 },
      { question_id: "a13", answer: 2, marks_awarded: 2 },
      { question_id: "a14", answer: 1, marks_awarded: 2 },
      { question_id: "a15", answer: 3, marks_awarded: 2 },
      { question_id: "a16", answer: 1, marks_awarded: 2 },
      { question_id: "a17", answer: 1, marks_awarded: 2 },
      { question_id: "a18", answer: 2, marks_awarded: 2 },
      { question_id: "a19", answer: 0, marks_awarded: 2 },
      { question_id: "a20", answer: 3, marks_awarded: 2 },
    ],
    section_b: [
      { question_id: "b1", answer: "Encapsulation: bundling data and methods (e.g., a Car class with speed and accelerate()). Inheritance: child class inherits parent (e.g., ElectricCar extends Car). Polymorphism: same method, different behavior (e.g., speak() for Dog and Cat). Abstraction: hiding complexity (e.g., using a TV remote without knowing circuits).", marks_awarded: 29 },
      { question_id: "b2", answer: "OSI 7 layers: Physical (cables, fiber), Data Link (Ethernet, MAC), Network (IP, routers), Transport (TCP, UDP, port numbers), Session (manages connections), Presentation (SSL, encoding), Application (HTTP, FTP, DNS, SMTP).", marks_awarded: 29 },
    ],
    status: "graded",
    total_score: 98,
    created_at: "2024-01-20T11:30:00Z",
  },
  {
    id: "sub-006",
    unit_code: "COMP-204",
    student_name: "Francis Mwangi Kariuki",
    reg_number: "MTTI/2024/006",
    section_a: Array.from({ length: 20 }, (_, i) => ({
      question_id: `a${i + 1}`,
      answer: i % 3,
      marks_awarded: i % 4 === 0 ? 0 : 2,
    })),
    section_b: [
      { question_id: "b1", answer: "OOP has encapsulation and inheritance.", marks_awarded: 12 },
      { question_id: "b3", answer: "SQL uses tables, NoSQL uses documents.", marks_awarded: 14 },
    ],
    status: "pending",
    total_score: null,
    created_at: "2024-01-20T12:00:00Z",
  },
  {
    id: "sub-007",
    unit_code: "ELEC-101",
    student_name: "Grace Wambui Maina",
    reg_number: "MTTI/2024/007",
    section_a: [
      { question_id: "a1", answer: 2, marks_awarded: 2 },
      { question_id: "a2", answer: 1, marks_awarded: 2 },
      { question_id: "a3", answer: 2, marks_awarded: 2 },
      { question_id: "a4", answer: 1, marks_awarded: 2 },
      { question_id: "a5", answer: 2, marks_awarded: 2 },
    ],
    section_b: [
      { question_id: "b1", answer: "Ring main circuit connects all sockets in a ring. Use 2.5mm² cable. Safety: isolate supply, test with multimeter, use RCD.", marks_awarded: 24 },
    ],
    status: "graded",
    total_score: 34,
    created_at: "2024-01-25T09:00:00Z",
  },
];
